kind: pipeline
type: docker
name: default
steps:
  - name: test
    image: gcc:10
    commands:
      - apt-get update
      - apt-get install cmake
      - mkdir build && cd build
      - cmake .. && make
      - ./runUnitTests
