kind: pipeline
type: docker
name: default
steps:
  - name: test
    image: gcc:10
    commands:
      - git submodule update --init --recursive
      - apt-get update
      - apt-get install cmake -y
      - mkdir build && cd build
      - cmake .. && make
      - make check-tests
